name: Auto Merge PRs for bvc-sa-gqe

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Merge if PR opened by viveksree1
        if: ${{ github.event.pull_request.user.login == 'viveksree1' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "Merging PR #$PR_NUMBER created by viveksree1"
          gh pr merge --auto --squash "$PR_NUMBER" --repo "${{ github.repository }}"
