name: Auto Merge PRs for viveksree1

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
    
      - name: Fetch PR Details
        id: pr_details
        run: |
          PR_CREATOR=$(gh pr view "${{ github.event.pull_request.number }}" --json author --jq '.author.login')
          echo "PR_CREATOR=$PR_CREATOR" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge if PR was created by viveksree1
        if: ${{ env.PR_CREATOR == 'viveksree1' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "Merging PR #$PR_NUMBER created by viveksree1"
          gh pr merge --auto --squash "$PR_NUMBER" --repo "${{ github.repository }}"
